"""
report_agent_stub.py

Renders ComparisonResult into an analyst-style PDF using ReportLab.
Supports both pairwise (2-company) and multi-company peer benchmarking.
"""

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
)

FLAG_COLOR = {
    "outperform": colors.HexColor("#166534"),
    "underperform": colors.HexColor("#991b1b"),
    "inline": colors.HexColor("#334155"),
    "no_data": colors.HexColor("#94a3b8"),
}
FLAG_LABEL = {
    "outperform": "Outperforms",
    "underperform": "Underperforms",
    "inline": "In line",
    "no_data": "No Data",
}


def render_comparison_pdf(result, out_path: str, source_docs: str = "nexacore_financial_document_final.pdf, infoedge_financial_document.pdf"):
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TitleX", parent=styles["Title"], fontSize=18, leading=22, textColor=colors.HexColor("#0f172a"))
    h2 = ParagraphStyle("H2", parent=styles["Heading2"], fontSize=12, leading=15, spaceBefore=14, spaceAfter=6, textColor=colors.HexColor("#1e293b"))
    body = ParagraphStyle("BodyX", parent=styles["Normal"], fontSize=9.5, leading=14, textColor=colors.HexColor("#334155"))

    doc = SimpleDocTemplate(
        out_path,
        pagesize=A4,
        topMargin=1.8 * cm,
        bottomMargin=1.8 * cm,
        leftMargin=1.6 * cm,
        rightMargin=1.6 * cm
    )
    story = []

    story.append(Paragraph("Financial Document Benchmarking & Comparison Report", title_style))
    story.append(Spacer(1, 4))

    peers = [c for c in result.companies_compared if c != result.focus_company]
    peer_str = ", ".join(peers)

    story.append(Paragraph(
        f"<b>Focus Company:</b> {result.focus_company} &nbsp;|&nbsp; "
        f"<b>Fiscal Year:</b> {result.fiscal_year} &nbsp;|&nbsp; "
        f"<b>Comparison Target(s):</b> {peer_str}",
        body
    ))
    story.append(Spacer(1, 10))

    story.append(Paragraph("Executive Summary & Narrative Synthesis", h2))
    story.append(Paragraph(result.narrative_summary, body))
    story.append(Spacer(1, 8))

    if result.key_strengths:
        story.append(Paragraph(
            "<b>Key Strengths vs Target:</b> " + ", ".join(result.key_strengths), body
        ))
    if result.key_weaknesses:
        story.append(Paragraph(
            "<b>Key Weaknesses vs Target:</b> " + ", ".join(result.key_weaknesses), body
        ))

    story.append(Spacer(1, 10))
    story.append(Paragraph("Side-by-Side Financial Metric Comparison", h2))

    peer_header = peers[0] if len(peers) == 1 else "Peer Avg"
    table_data = [["Financial Metric", result.focus_company, peer_header, "Variance (%)", "Rank", "Assessment"]]

    for m in result.metric_comparisons:
        rank_str = f"{m.focus_rank}/{m.total_ranked}" if m.focus_rank else "-"
        diff_str = f"{m.focus_vs_peer_avg_pct:+.1f}%" if m.focus_vs_peer_avg_pct is not None else "-"
        table_data.append([
            m.metric,
            f"{m.focus_company_value:,.1f}" if m.focus_company_value is not None else "-",
            f"{m.peer_average:,.1f}" if m.peer_average is not None else "-",
            diff_str,
            rank_str,
            FLAG_LABEL[m.flag],
        ])

    tbl = Table(table_data, colWidths=[5.2 * cm, 2.8 * cm, 2.8 * cm, 2.4 * cm, 1.8 * cm, 3.0 * cm])
    style_cmds = [
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f172a")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 8.5),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cbd5e1")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]

    for row_idx, m in enumerate(result.metric_comparisons, start=1):
        style_cmds.append(("TEXTCOLOR", (5, row_idx), (5, row_idx), FLAG_COLOR[m.flag]))
        style_cmds.append(("FONTNAME", (5, row_idx), (5, row_idx), "Helvetica-Bold"))

    tbl.setStyle(TableStyle(style_cmds))
    story.append(tbl)

    story.append(Spacer(1, 14))
    story.append(Paragraph(
        f"<b>Source Documents:</b> {source_docs}. Generated by Comparison Agent.",
        ParagraphStyle("Footnote", parent=styles["Normal"], fontSize=8, textColor=colors.HexColor("#64748b"))
    ))

    doc.build(story)
    print(f"Comparison report PDF written to {out_path}")
